import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import { Poppins } from "next/font/google";
import { ThemeProvider } from "@/app/context/ThemeContext";
import ThemeSwitcher from "@/components/ThemeSwitcher";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  variable: '--font-poppins',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        
        <ThemeProvider>
           <ThemeSwitcher /> 
          <Sidebar />   {/* ✔ VALID HERE */}
          {children}
        </ThemeProvider>

      </body>
    </html>
  );
}
